### ISSUE TITLE
Server regularly crashes

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-www#32]
We have supervisor listening to automatically restart the server, but we should prevent the crashes because they cause the site to be intermittently unavailable.

```
Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at Socket.socketCloseListener (_http_client.js:235:23)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

**Comment by feross** [comment]
Confirmed this is fixed now.

```
==> www/log/webtorrent.io/site.log <==
Sun, 22 Nov 2015 20:17:00 GMT webtorrent-www:tracker warning: no peer with that `to_peer_id`
Sun, 22 Nov 2015 20:17:00 GMT webtorrent-www:tracker warning: no peer with that `to_peer_id`
Sun, 22 Nov 2015 20:17:09 GMT webtorrent-www:tracker warning: no peer with that `to_peer_id`
Sun, 22 Nov 2015 20:18:02 GMT webtorrent-www:router [proxy error] GET /torrents/sintel-1024-surround.mp4 socket hang up
Sun, 22 Nov 2015 20:19:30 GMT webtorrent-www:tracker warning: no peer with that `to_peer_id`
Sun, 22 Nov 2015 20:20:53 GMT webtorrent-www:router [proxy error] GET /torrents/sintel-1024-surround.mp4 socket hang up
Sun, 22 Nov 2015 20:20:56 GMT webtorrent-www:tracker warning: no peer with that `to_peer_id`
Sun, 22 Nov 2015 20:21:06 GMT webtorrent-www:tracker warning: no peer with that `to_peer_id`
Sun, 22 Nov 2015 20:21:07 GMT webtorrent-www:tracker warning: no peer with that `to_peer_id`
```

No server crash now.
